RotaLoginMVC/Controllers/CitiesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RotaLoginMVC.Models;
using RotaLoginMVC.Services;

namespace RotaLoginMvc.Controllers
{
    public class CitiesController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var cities = await CitiesService.Get();

            return View(cities);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction(nameof(Index));

            var city = await CitiesService.Get(id);

            return View(city);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,State")] CityViewModel city)
        {
            if (ModelState.IsValid)
            {
                var cityExist = await CitiesService.GetByName(city.Name.ToUpper());

                if (cityExist.Id != null)
                    return View(city);

                city.Name = city.Name.ToUpper().Trim();
                city.State = city.State.ToUpper().Trim();

                await CitiesService.Create(city);

                return RedirectToAction(nameof(Index));
            }

            return View(city);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction(nameof(Index));

            var person = await CitiesService.Get(id);

            return View(person);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,State")] CityViewModel city)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(city.Name) || string.IsNullOrEmpty(city.State))
                    return View(city);

                var response = await CitiesService.Update(id, city);

                if (response.IsSuccessStatusCode)
                    return RedirectToAction(nameof(Index));
            }

            return View(city);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction(nameof(Index));

            var response = await CitiesService.Delete(id);

            if (response.IsSuccessStatusCode)
                return RedirectToAction(nameof(Index));

            return View();
        }
    }
}

RotaLoginMVC/Controllers/FilesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using RotaLoginMVC.Models;
using RotaLoginMVC.Services;

namespace RotaLoginMVC.Controllers
{
    public class FilesController : Controller
    {
        public static List<List<string>> routes = new();
        public static List<string> headers = new();
        public static List<string> services = new();
        public static string serviceName;
        public static string cityId;

        public IActionResult Upload()
        {
            return View();
        }
        public IActionResult UploadFile()
        {
            var files = HttpContext.Request.Form.Files;

            if (files.Count > 0)
            {
                List<List<string>> routesFromExcel = new();
                List<string> headersFromExcel = new();

                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                using ExcelPackage package = new(files[0].OpenReadStream());
                ExcelWorksheet worksheet = package.Workbook.Worksheets.FirstOrDefault();

                var columnCount = worksheet.Dimension.End.Column;
                var rowCount = worksheet.Dimension.End.Row;

                int columnCep = 0;
                int columnService = 0;

                for (var column = 1; column < columnCount; column++)
                {
                    headersFromExcel.Add(worksheet.Cells[1, column].Value.ToString());

                    if (worksheet.Cells[1, column].Value.ToString().ToUpper().Equals("CEP"))
                        columnCep = column - 1;

                    if (worksheet.Cells[1, column].Value.ToString().ToUpper().Equals("SERVIÇO"))
                        columnService = column;
                }

                headers = headersFromExcel;

                worksheet.Cells[2, 1, rowCount, columnCount].Sort(columnCep, false);

                List<string> servicesRaw = new();

                for (var row = 1; row < rowCount; row++)
                {
                    List<string> rowContent = new();

                    for (var column = 1; column < columnCount; column++)
                    {
                        servicesRaw.Add(worksheet.Cells[row, columnService].Value.ToString().ToUpper());

                        var content = worksheet.Cells[row, column].Value?.ToString() ?? "";
                        rowContent.Add(content.ToString());
                    }

                    routesFromExcel.Add(rowContent);
                }

                services = servicesRaw.Distinct().ToList();
                services.RemoveAt(0);

                routes = routesFromExcel;

                return RedirectToAction(nameof(OperatingCity));
            }

            return RedirectToAction(nameof(Upload));
        }

        public async Task<IActionResult> OperatingCity()
        {
            IEnumerable<CityViewModel> cities = await CitiesService.Get();

            ViewBag.Cities = cities;
            ViewBag.Services = services;

            return View();
        }

        [HttpPost]
        public IActionResult GetTeamsByOperatingCity()
        {
            serviceName = Request.Form["serviceName"].ToString();
            cityId = Request.Form["OperatingCity"].ToString();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<TeamViewModel> teams = await TeamsService.GetTeamsByCity(cityId);

            var teamsAvailable =
                (from team in teams
                 where team.IsAvailable == true
                 select team);

            ViewBag.TeamsAvailable = teamsAvailable;
            ViewBag.Headers = headers;

            return View();
        }

        public async Task<IActionResult> Create()
        {
            var teamsOptionsSelected = Request.Form["checkTeams"].ToList();
            var dataOptionsSelected = Request.Form["checkData"].ToList();

            if (teamsOptionsSelected.Count == 0 || dataOptionsSelected.Count == 0)
                return RedirectToAction(nameof(Index));

            List<TeamViewModel> teamsSelected = new();

            foreach (var teamId in teamsOptionsSelected)
            {
                var team = await TeamsService.Get(teamId);
                teamsSelected.Add(team);
            }

            var citySelected = await CitiesService.Get(cityId);
            await GenerateDoc.Write(routes, dataOptionsSelected, teamsSelected, serviceName, citySelected);
            return View();
        }
    }
}

RotaLoginMVC/Controllers/TeamsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RotaLoginMVC.Models;
using RotaLoginMVC.Services;

namespace RotaLoginMVC.Controllers
{
    public class TeamsController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var teams = await TeamsService.Get();

            return View(teams);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction(nameof(Index));

            var team = await TeamsService.Get(id);

            return View(team);
        }

        public async Task<IActionResult> Create()
        {
            IEnumerable<PersonViewModel> peopleAvailable = await GetPeopleAvailable();

            IEnumerable<CityViewModel> cities = await CitiesService.Get();

            ViewBag.PeopleAvailable = peopleAvailable;
            ViewBag.Cities = cities;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name, IsAvailable")] TeamViewModel team)
        {
            List<PersonViewModel> peopleSelected = new();

            if (ModelState.IsValid)
            {
                var operatingCityId = Request.Form["OperatingCity"].FirstOrDefault();

                var operatingCity = await CitiesService.Get(operatingCityId);

                if (operatingCity == null)
                    return RedirectToAction(nameof(Create));

                if (Request.Form["checkPeopleTeam"].ToList().Count == 0)
                    return RedirectToAction(nameof(Create));

                foreach (var person_id in Request.Form["checkPeopleTeam"].ToList())
                {
                    var person = await PeopleService.Get(person_id.ToString());
                    peopleSelected.Add(new PersonViewModel(person.Id, person.Name, person.IsAvailable));
                }

                team.People = peopleSelected;
                team.OperatingCity = operatingCity;

                await TeamsService.Create(team);

                return RedirectToAction(nameof(Index));
            }

            return View(team);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction(nameof(Index));

            var team = await TeamsService.Get(id);

            var people = await PeopleService.Get();

            var peopleAvailable =
                (from person in people
                 where person.IsAvailable == true
                 select person);

            IEnumerable<CityViewModel> cities = await CitiesService.Get();

            ViewBag.PeopleAvailable = peopleAvailable;
            ViewBag.Cities = cities;

            List<PersonViewModel> peopleTeam = new();

            foreach (var person in team.People)
                peopleTeam.Add(new PersonViewModel(person.Id, person.Name, person.IsAvailable));

            ViewBag.PeopleAvailable = peopleAvailable;
            ViewBag.PeopleTeam = peopleTeam;

            return View(team);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, TeamViewModel team)
        {
            var operatingCity = await CitiesService.Get(team.OperatingCity.Id);

            if (operatingCity == null)
                return RedirectToAction(nameof(Create));

            team.OperatingCity = operatingCity;

            var peopleToAdd = Request.Form["checkPeopleAvailableToAdd"].ToList();
            var peopleToRemove = Request.Form["checkPeopleTeamToRemove"].ToList();

            if (peopleToAdd.Count != 0)
                foreach (var person_id in Request.Form["checkPeopleAvailableToAdd"].ToList())
                {
                    var person = await PeopleService.Get(person_id.ToString());

                    await TeamsService.UpdateInsert(id, person);
                }

            if (peopleToRemove.Count != 0)
                foreach (var person_id in Request.Form["checkPeopleTeamToRemove"].ToList())
                {
                    var person = await PeopleService.Get(person_id.ToString());

                    await TeamsService.UpdateRemove(id, person);
                }

            var response = await TeamsService.Update(id, team);

            if (response.IsSuccessStatusCode)
                return RedirectToAction(nameof(Index));

            return View(team);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction(nameof(Index));

            var response = await TeamsService.Delete(id);

            if (response.IsSuccessStatusCode)
                return RedirectToAction(nameof(Index));

            return View();
        }



        private static async Task<IEnumerable<PersonViewModel>> GetPeopleAvailable()
        {
            var people = await PeopleService.Get();

            var peopleAvailable =
                (from person in people
                 where person.IsAvailable == true
                 select person);

            return peopleAvailable;
        }
    }
}

RotaLoginMVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RotaLoginMVC.Models;
using System.Threading.Tasks;

namespace RotaLoginMVC.Controllers
{
    public class UserController : Controller
    {
        private UserManager<ApplicationUser> _userManager;
        private RoleManager<ApplicationRole> _roleManager;
        public UserController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserViewModel user)
        {
            ApplicationUser appUser = new ApplicationUser
            {
                UserName = user.Name,
                Email = user.Email
            };

            IdentityResult result = await _userManager.CreateAsync(appUser, user.Password);

            if (result.Succeeded)
            {
                ViewBag.Message = "Usuário Cadastrado Com Sucesso";
            }
            else
            {
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(user);
        }
    }
}

RotaLoginMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RotaLoginMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RotaLoginMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br />
    <br />
    <footer class="border-top footer text-muted">
        <div class="container" style="text-align:center;">
            &copy; 2022 - RotaLoginMVC - Todos os direitos reservados a Antonio e 5by5
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RotaLoginMVC/Views/Shared/_LayoutLogado.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RotaLoginMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="AccessAllowed">RotaLoginMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">Pessoas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Index">Equipes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Index">Cidades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Files" asp-action="Upload">Rotas</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">Cadastrar Usuário</a>
                        </li>
                        @{
                        if (!User?.Identity?.IsAuthenticated ?? false)
                        {
                            Layout = "~/Views/Shared/_Layout.cshtml";
                            <meta http-equiv='refresh' content='0; URL= https://localhost:44317/Account/Login'>
                        }else{  
                            <li style = "margin-left: auto;" class="nav-item">
                            <u style = "text-decoration: none; padding-right: 20px">Bem-Vindo: @User.Identity.Name</u>
                            <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Sair</a>
                            </li>
                   }
            }
                    </ul>
                </div>
                </div>
                 </nav> 
                   </header>
                        <div class="container">
                        <main role="main" class="pb-3">
                            @RenderBody()
                        </main>
                    </div>
                    <br />
                    <br />
                <footer class="border-top footer">
                    <div class="container" style="text-align:center;">
                        &copy; 2022 - RotaLoginMVC - Todos os direitos reservados a Antonio e 5by5
                    </div>
                </footer>   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RotaLoginMVC/Views/Shared/_LayoutWithLogin.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RotaLoginMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RotaLoginMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="text-align:center;">
            &copy; 2022 - RotaLoginMVC - Todos os direitos reservados a Antonio e 5by5
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>